### ISSUE TITLE
[ Probation/试用 ] 一些问题/lack of demo program

### ISSUE THREAD

**Issue by Xzzuh** [Super-Badmen-Viper/MoZhiMusicPlayer#19]
我在闲暇时稍微试用了一下Releases中的demo
发现如下：
1. 点击歌曲缩略图后打开了动态播放的界面，这没问题。但！**再次点击同一个地方无法退出该界面**，必须点击远在左上角的>按钮
2. 不能向主界面拖放歌曲文件及文件夹以添加歌曲
3. 同上，甚至在添加歌曲的专用界面（那个很多文本框的界面）也不行！！
4. 添加音乐时若保持默认设置，音乐会进入“我的收藏”，而所谓的“本地音乐”里没有出现（那难道刚才那首歌不存储在我的设备上了吗？这属于逻辑谬论）
5. 进度条仅在点击时响应，拖动无效
6. 最重要的，不能读取.MP3内嵌的歌词（我亲手写了150+份内嵌逐字时间轴歌词）
7. 似乎  封面也不能内嵌
8. 调节音量后不会自动收起，并且点击空白处不能收起音量控件
9. 音量控件不支持点击快速静音
10. 重新进入程序直接点击开始播放 无动作。此时检查播放列表为空（具体说就是不会记住上次运行的列表并且在列表为空时自动生成新表）
11. 同上，重新进入程序直接点击开始播放 无动作，**但播放按钮却已经变成正在播放的样式**
12. 不存在收起到任务栏右侧隐藏后台程序的功能（你可以理解为像挂QQ一样）

暂时以上，
       加油

**Comment by Super-Badmen-Viper** [comment]
好的，已经收到，因为是我一个人编写，所以还有很多不足的地方，这些BUG和不足的地方我将一一改进

**Comment by Super-Badmen-Viper** [comment]
> 我在闲暇时稍微试用了一下Releases中的demo 发现如下：
> 
> 1. 点击歌曲缩略图后打开了动态播放的界面，这没问题。但！**再次点击同一个地方无法退出该界面**，必须点击远在左上角的>按钮
> 2. 不能向主界面拖放歌曲文件及文件夹以添加歌曲
> 3. 同上，甚至在添加歌曲的专用界面（那个很多文本框的界面）也不行！！
> 4. 添加音乐时若保持默认设置，音乐会进入"我的收藏"，而所谓的"本地音乐"里没有出现（那难道刚才那首歌不存储在我的设备上了吗？这属于逻辑谬论）
> 5. 进度条仅在点击时响应，拖动无效
> 6. 最重要的，不能读取.MP3内嵌的歌词（我亲手写了150+份内嵌逐字时间轴歌词）
> 7. 似乎  封面也不能内嵌
> 8. 调节音量后不会自动收起，并且点击空白处不能收起音量控件
> 9. 音量控件不支持点击快速静音
> 10. 重新进入程序直接点击开始播放 无动作。此时检查播放列表为空（具体说就是不会记住上次运行的列表并且在列表为空时自动生成新表）
> 11. 同上，重新进入程序直接点击开始播放 无动作，**但播放按钮却已经变成正在播放的样式**
> 12. 不存在收起到任务栏右侧隐藏后台程序的功能（你可以理解为像挂QQ一样）
> 
> 暂时以上， 加油

已经收到，我将逐一改进这些不足和BUG，并对你的建议表示感谢

**Comment by Super-Badmen-Viper** [comment]
> ![图像](https://user-images.githubusercontent.com/88430768/261967312-3b9c7e99-10cf-4b92-875b-c9957d6688a1.png)当使用 人类易读的时间轴格式时解析崩溃`[00:05.41]<00:05.41>词<00:06.02>：<00:06.62>王<00:07.22>力<00:07.82>宏`
> 
> 我知道拓展名不同，但是lrc相当于歌词界的Json文本。

我将改进该应用对lrc的各种支持，比如从音乐文件中读取lrc歌词等。后续将开发AI模型，既使用lrc歌词的情况下，仍然可以实现精准的歌词逐字同步效果。感谢你的建议

**Comment by Xzzuh** [comment]
好的，没问题
但有一件事我必须提醒你：
## lrc也可以实现逐字功能 ##
### 无论是LRC、TRC、KRC、QRC、KSC、KAJ都支持逐字 ###
他们之间的区别可以参见[https://shansing.com/read/392/](https://shansing.com/read/392/)

逐字与否跟文件类型和文件编码完全无关，关键因素是`[xxxx]<xxxx>`这一类的时间轴标签
如果删除他们，krc也一样会变成静止的文本类。你可以试试

综上所述，**解释器** 才是是否支持逐字的根本。无论是设定单字持续时间，还是设定平均时间，都没有关系
### 在单字持续时间时，我作为歌词打轴者 可以这样写 ###
```
[行绝对时间, 持续时间]<字绝对时间, 持续时间>A.<字绝对时间, 持续时间>I.<字绝对时间, 持续时间>N.<字绝对时间, 持续时间>Y.
[行绝对时间, 持续时间]<字绝对时间, 持续时间>邓<字绝对时间, 持续时间>紫<字绝对时间, 持续时间>棋
```
### 在平均持续时间时，我作为歌词打轴者 可以这样写 ###
```
[00:03.45]分开以后每个夜晚<00:06.60><00:07.00>格外的<00:08.30>寂静<00:08.90>
[行起始时间]滴答滴答<字起始时间> <字起始时间>剩大钟<字起始时间>在<字起始时间>陪着我<字起始时间>回忆<字起始时间>
[00:17.10]电话里头曾经是<00:20.15>你最温柔的声<00:22.50>音<00:23.30>
```
原理就是卡点而已，把字真正发出声音的时间记录上去，比如<00:06.60><00:07.00>其中相当于06.60~07.00之间的时间是静止不动的
如果你缺少实验用的lrc，可以找我提供。我有很多

**Comment by Super-Badmen-Viper** [comment]
> 好的，没问题 但有一件事我必须提醒你：
> 
> ## lrc也可以实现逐字功能
> ### 无论是LRC、TRC、KRC、QRC、KSC、KAJ都支持逐字
> 他们之间的区别可以参见https://shansing.com/read/392/
> 
> 逐字与否跟文件类型和文件编码完全无关，关键因素是`[xxxx]<xxxx>`这一类的时间轴标签 如果删除他们，krc也一样会变成静止的文本类。你可以试试
> 
> 综上所述，**解释器** 才是是否支持逐字的根本。无论是设定单字持续时间，还是设定平均时间，都没有关系
> 
> ### 在单字持续时间时，我作为歌词打轴者 可以这样写
> ```
> [行绝对时间, 持续时间]<字绝对时间, 持续时间>A.<字绝对时间, 持续时间>I.<字绝对时间, 持续时间>N.<字绝对时间, 持续时间>Y.
> [行绝对时间, 持续时间]<字绝对时间, 持续时间>邓<字绝对时间, 持续时间>紫<字绝对时间, 持续时间>棋
> ```
> 
> ### 在平均持续时间时，我作为歌词打轴者 可以这样写
> ```
> [00:03.45]分开以后每个夜晚<00:06.60><00:07.00>格外的<00:08.30>寂静<00:08.90>
> [行起始时间]滴答滴答<字起始时间> <字起始时间>剩大钟<字起始时间>在<字起始时间>陪着我<字起始时间>回忆<字起始时间>
> [00:17.10]电话里头曾经是<00:20.15>你最温柔的声<00:22.50>音<00:23.30>
> ```
> 
> 原理就是卡点而已，把字真正发出声音的时间记录上去，比如<00:06.60><00:07.00>其中相当于06.60~07.00之间的时间是静止不动的 如果你缺少实验用的lrc，可以找我提供。我有很多

OK，我已经了解了，你可以把你的不同逐字格式的lrc弄成压缩包，发送到我的邮箱，我将使用它们，使其能兼容我的程序（邮箱：1774148579@qq.com  或者   xiangch007@gmail.com）
我还将开发 开源的 逐字歌词信息生成模型，它可以帮助你及其它的歌词打轴者等音乐爱好及专业者 ，提供AI生成歌词信息的便利，免去繁琐的大部分制作过程，它的格式将我将命名为mrc(不加密开源免费)
至此，感谢你的建议，我将逐一采纳

**Comment by Super-Badmen-Viper** [comment]
> 我在闲暇时稍微试用了一下Releases中的demo 发现如下：
> 
> 1. 点击歌曲缩略图后打开了动态播放的界面，这没问题。但！**再次点击同一个地方无法退出该界面**，必须点击远在左上角的>按钮
> 2. 不能向主界面拖放歌曲文件及文件夹以添加歌曲
> 3. 同上，甚至在添加歌曲的专用界面（那个很多文本框的界面）也不行！！
> 4. 添加音乐时若保持默认设置，音乐会进入“我的收藏”，而所谓的“本地音乐”里没有出现（那难道刚才那首歌不存储在我的设备上了吗？这属于逻辑谬论）
> 5. 进度条仅在点击时响应，拖动无效
> 6. 最重要的，不能读取.MP3内嵌的歌词（我亲手写了150+份内嵌逐字时间轴歌词）
> 7. 似乎  封面也不能内嵌
> 8. 调节音量后不会自动收起，并且点击空白处不能收起音量控件
> 9. 音量控件不支持点击快速静音
> 10. 重新进入程序直接点击开始播放 无动作。此时检查播放列表为空（具体说就是不会记住上次运行的列表并且在列表为空时自动生成新表）
> 11. 同上，重新进入程序直接点击开始播放 无动作，**但播放按钮却已经变成正在播放的样式**
> 12. 不存在收起到任务栏右侧隐藏后台程序的功能（你可以理解为像挂QQ一样）
> 
> 暂时以上， 加油

你所提出的问题，我已经解决了大半，但是我这边缺少自带歌词和专辑图片的歌曲文件（如mp3），以及各类支持逐字效果的歌词文件（如lrc等），所以关于提取歌曲文件内信息的功能暂时不能继续，需要有你提出的这种自带歌词和专辑图片的歌曲文件及歌词文件。
如果你将以上这些我需要的文件压缩发送至我的邮箱，你提出的所有问题建议都将被解决采纳

**Comment by Super-Badmen-Viper** [comment]
> 我在闲暇时稍微试用了一下Releases中的demo 发现如下：
> 
> 1. 点击歌曲缩略图后打开了动态播放的界面，这没问题。但！**再次点击同一个地方无法退出该界面**，必须点击远在左上角的>按钮
> 2. 不能向主界面拖放歌曲文件及文件夹以添加歌曲
> 3. 同上，甚至在添加歌曲的专用界面（那个很多文本框的界面）也不行！！
> 4. 添加音乐时若保持默认设置，音乐会进入“我的收藏”，而所谓的“本地音乐”里没有出现（那难道刚才那首歌不存储在我的设备上了吗？这属于逻辑谬论）
> 5. 进度条仅在点击时响应，拖动无效
> 6. 最重要的，不能读取.MP3内嵌的歌词（我亲手写了150+份内嵌逐字时间轴歌词）
> 7. 似乎  封面也不能内嵌
> 8. 调节音量后不会自动收起，并且点击空白处不能收起音量控件
> 9. 音量控件不支持点击快速静音
> 10. 重新进入程序直接点击开始播放 无动作。此时检查播放列表为空（具体说就是不会记住上次运行的列表并且在列表为空时自动生成新表）
> 11. 同上，重新进入程序直接点击开始播放 无动作，**但播放按钮却已经变成正在播放的样式**
> 12. 不存在收起到任务栏右侧隐藏后台程序的功能（你可以理解为像挂QQ一样）
> 
> 暂时以上， 加油

此Issuea内提出的所有建议，我已全部解决，感谢您的建议
