### ISSUE TITLE
{开源，共建}不再仿制QQ音乐UI，将自定义更炫酷更具音乐技术的UI，欢迎提交pull你的UI创意

### ISSUE THREAD

**Issue by Super-Badmen-Viper** [Super-Badmen-Viper/MoZhiMusicPlayer#8]

**Comment by Xzzuh** [comment]
UI是个大难题
我认为可以去搜索及浏览Foobar2000的庞大皮肤社区，里面有很多好的作品（也许运行会很卡），但绝对够炫酷
先挑几版留着参考，日后最终决定再考虑

比如：

- https://vsthemes.org/en/skins/foobar2000/page/2/
- https://tieba.baidu.com/p/7908012512#/
- https://www.bilibili.com/video/BV1ED4y1q7B8
- https://tieba.baidu.com/p/6325835077
- https://www.52pojie.cn/thread-1726106-1-1.html

除此之外我还见过一款国人皮肤作品。模拟实体解码器功放设备的，非常精致。但我找不到来源了，抱歉

**Comment by Super-Badmen-Viper** [comment]
> UI是个大难题 我认为可以去搜索及浏览Foobar2000的庞大皮肤社区，里面有很多好的作品（也许运行会很卡），但绝对够炫酷 先挑几版留着参考，日后最终决定再考虑
> 
> 比如：
> 
> * https://vsthemes.org/en/skins/foobar2000/page/2/
> * https://tieba.baidu.com/p/7908012512#/
> * https://www.bilibili.com/video/BV1ED4y1q7B8
> * https://tieba.baidu.com/p/6325835077
> * https://www.52pojie.cn/thread-1726106-1-1.html
> 
> 除此之外我还见过一款国人皮肤作品。模拟实体解码器功放设备的，非常精致。但我找不到来源了，抱歉

好的，我将参考你的意见前去借鉴这些UI创意
